### ISSUE TITLE
Find a way to not need `CAP_SYS_ADMIN`

### ISSUE THREAD

**Issue by dgtlmoon** [dgtlmoon/sockpuppetbrowser#1]
CAP_SYS_ADMIN is too powerful

**Comment by dgtlmoon** [comment]
resolved with `seccomp`

**Comment by hanjo** [comment]
Also still listed here:
https://github.com/dgtlmoon/sockpuppetbrowser/blob/master/docker-compose.yml

A better explanation would be great :-)

**Comment by ilovelinux** [comment]
> Could some more information be shared on how to limit the container's required privileges? What profile do you use?

It's described in https://github.com/dgtlmoon/sockpuppetbrowser?tab=readme-ov-file#how-to-run
